version: 0.0
os: linux
files:
  - source: /website.war
    destination: /tmp/codedeploy-deployment-staging-area/
  - source: /scripts1/changePort.sh
    destination: /tmp/codedeploy-deployment-staging-area/
hooks:
  ApplicationStop:
    - location: scripts1/stop_application
      timeout: 300
  BeforeInstall:
    - location: scripts1/install_dependencies
    - location: scripts1/changePort.sh
      timeout: 300
  ApplicationStart:
    - location: scripts1/write_codedeploy_config.sh
    - location: scripts1/start_application
      timeout: 300
  ValidateService:
    - location: scripts1/basic_health_check.sh
