version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html
hooks:
BeforeInstall:
    - location: scripts1/install_dependencies
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts1/start_application
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts1/stop_application
      timeout: 300
      runas: root
